name: 'vcpkg-registry-update'
description: 'Updates PazerOP/vcpkg-registry'
inputs:
  port-name:
    description: 'Name of the port'
    required: true
  port-ref:
    description: 'Ref of the port'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        repository: PazerOP/vcpkg-registry
        path: vcpkg-registry

    - name: Setup NuGet Credentials
      shell: bash
      run: >
        nuget sources add
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        -storepasswordincleartext
        -name "GitHub"
        -username "${{ github.repository_owner }}"
        -password "${{ secrets.GITHUB_TOKEN }}"

    - run: ${{ github.action_path }}/update-registry.ps1 -PortName "${{ inputs.port-name }}" -PortRef "${{ inputs.port-ref }}"
      shell: pwsh
