name: 'vcpkg-registry-update'
description: 'Triggers a workflow dispatch for this port'
inputs:
  port-name:
    description: 'Name of the port'
    required: true
  port-ref:
    description: 'Ref of the port'
    required: true
    default: ${{ github.sha }}
  workflow-pat:
    description: 'Personal access token that has permissions to start a workflow'
    required: true

runs:
  using: "composite"
  steps:
    - name: Debug
      shell: bash
      run: |
        echo "github.repository = ${{ github.repository }}"

    - name: Trigger update workflow
      shell: bash
      run: >
        curl
        -u PazerOP:${{ inputs.workflow-pat }}
        -X POST
        -H "Accept: application/vnd.github.v3+json"
        https://api.github.com/repos/PazerOP/vcpkg-registry/actions/workflows/update_registry.yml/dispatches
        -d '{ "ref":"main", "inputs":{ "port-name":"${{ inputs.port-name }}", "port-ref":"${{ inputs.port-ref }}", "user-repo-name":"${{ github.repository }}"} }'

      # uses: benc-uk/workflow-dispatch@v1
      # with:
      #   repo: PazerOP/vcpkg-registry
      #   ref: main
      #   workflow: update_registry.yml
      #   token: ${{ inputs.workflow-pat }}
      #   inputs: '{ "port-name":"${{ inputs.port-name }}", "port-ref":"${{ inputs.port-ref }}" }'

